# Generated by Django 4.2 on 2024-11-22 11:32

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Name of the service', max_length=255)),
                ('slug', models.SlugField(help_text='Slug of the service for SEO purposes', max_length=255)),
                ('text', ckeditor.fields.RichTextField(help_text='Description of the service')),
            ],
        ),
    ]
