# Generated by Django 4.2 on 2024-11-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Experience',
        ),
    ]
