# Generated by Django 4.2 on 2024-11-22 11:39

from django.db import migrations, models
import experiences.models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_rename_service_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='excerpt',
            field=models.TextField(default='No excerpt provided', help_text='Short description of the service'),
        ),
        migrations.AddField(
            model_name='experience',
            name='thumbnail',
            field=models.ImageField(default='No thumbnail provided', help_text='Thumbnail of the experience', upload_to=experiences.models.Experience.get_path),
        ),
    ]
