# Generated by Django 4.2 on 2024-11-22 11:47

from django.db import migrations, models
import experiences.models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_experience_excerpt_experience_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='banner_image',
            field=models.ImageField(default='No banner image provided', help_text='Banner image of the experience', upload_to=experiences.models.Experience.get_path),
        ),
    ]
