# Generated by Django 5.1.3 on 2024-11-17 11:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
