# Generated by Django 4.2 on 2024-11-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0003_category_thought_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='excerpt',
            field=models.TextField(default='No excerpt provided', help_text='Small snippet of the thought for previews', max_length='220'),
        ),
    ]
